name: sinking_us
description: "Sinking Earth"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Google firebase
  firebase_core: ^2.21.0
  firebase_messaging: ^14.7.9
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.15.7 #firestore 서버
  firebase_database: ^10.3.4 #realtime firebase 서버
  flutter_local_notifications: ^16.3.0 #push notification
  firebase_storage: ^11.4.1
  cloud_functions: ^4.6.0

  #login
  google_sign_in: ^6.1.5 #구글 로그인
  sign_in_with_apple: ^5.0.0 #애플 로그인

  #Status management
  flutter_riverpod: 2.4.9 #상태관리 패키지
  riverpod_annotation: ^2.3.3 #riverpod
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #web
  url_strategy: ^0.2.0 #링크에 샵 삭제
  seo_renderer: ^0.6.0 #seo rendering

  #game
  flame: ^1.16.0
  flame_riverpod: ^5.2.0
  flame_audio: 2.10.1

  #etc
  flutter_screenutil: ^5.9.0 #화면 사이즈 controlling
  http: ^1.1.2
  cached_network_image: ^3.3.1 #web 로딩 속도 줄이기 & tick마다 새로그리기 방지
  flutter_svg: ^2.0.9 #svg 사용하기 위함
  shared_preferences: ^2.2.2 #tinydb
  flutter_secure_storage: ^9.0.0 #난독화 tinydb
  connectivity_plus: ^5.0.2 #인터넷 연결 상태 감지
  easy_localization: ^3.0.5 #지역 위치 파악 및 언어팩 연결
  intl: ^0.18.0 #다국어 및 다국 시간
  animated_text_kit: ^4.2.2 #애니메이션 텍스트
  lottie: ^3.1.0 #mp4 to json
  audioplayers: 5.2.1
  url_launcher: ^6.1.7 #링크 열기

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.6
  riverpod_lint: ^2.3.7
  freezed: ^2.4.7
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/characters/
    - assets/images/etc/
    - assets/images/store/
    - assets/images/policy/
    - assets/images/minigame/
    - assets/images/minigame/plug/
    - assets/images/minigame/sun/
    - assets/images/minigame/tree/
    - assets/images/minigame/trash/
    - assets/images/minigame/wind/
    - assets/images/minigame/water/
    - assets/svgs/
    - assets/translations/
    - assets/images/home/
    - assets/jsons/
    - assets/audio/

  fonts:
    - family: Galmuri
      fonts:
        - asset: assets/fonts/Galmuri9.ttf
